In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.2.2


# Introduction to Tensors

## Creating Tensors

Pytorch tensors are created using `torch.Tensor()` = https://pytorch.org/docs/stable/tensors.html



In [4]:
#Scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int
scalar.item()

7

In [7]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,8]])
MATRIX

tensor([[7, 8],
        [9, 8]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [10,12,19]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [10, 12, 19]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[ 1,  2,  3],
        [ 3,  6,  9],
        [10, 12, 19]])

## Random tensors

### Why Random Tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with tandom numbers -> look at data -> update random numbers -> look at data -> update the random number`

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [18]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8461, 0.2413, 0.0062, 0.7444],
        [0.3127, 0.2127, 0.0375, 0.1094],
        [0.3398, 0.2336, 0.2962, 0.8328]])

In [19]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224, 224)) # height, width, colour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros and ones

In [20]:
# Creat a tensor of all zeros
zero = torch.zeros(size=(3,4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
# create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [23]:
# Use torch.range()
zero_to_10 = torch.range(0, 11)
zero_to_10

/var/folders/fw/htgntw6x4zjg7_kmzsqdq39h0000gn/T/ipykernel_2769/2985049704.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_10 = torch.range(0, 11)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [24]:
# Use torch.arange
one_to_10 = torch.arange(0,11)
one_to_10

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
# Creating tensors like
ten_zeros = torch.zeros_like(input = one_to_10)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with PyTorch and deep learning which you might run into (it is more likely to cause errors)

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device


In [26]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what data type is tensor (e.g. float32, float16)
                               device=None,# what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [34]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [35]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

## Getting information from tensors (tensor atttributes)

1. Tensors not right datatype - to do get datatype of tensor, can use tensor.dtype
2. Tensors not right shape - to do get shape of tensor, can use tensor.shape
3. Tensors not on the right device - to do get device of tensor, can use tensor.device

In [37]:
# Create a tensor with 
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2677, 0.7757, 0.9315, 0.5743],
        [0.1296, 0.0217, 0.6811, 0.8889],
        [0.0011, 0.8906, 0.9820, 0.2282]])

In [39]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [40]:
# Find out detail about some_tensor
print(some_tensor)
print(f"DataType of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is stored on: {some_tensor.device}")

tensor([[0.2677, 0.7757, 0.9315, 0.5743],
        [0.1296, 0.0217, 0.6811, 0.8889],
        [0.0011, 0.8906, 0.9820, 0.2282]])
DataType of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is stored on: cpu


## Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise, matrix multiplication)
* Division
* Matrix multiplication



In [43]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [54]:
# Multuply tensor by 10
tensor * 10

tensor([100, 200, 300])

In [55]:
tensor # because we haven't re-assigned the variable tensor, the original value is still there

tensor([10, 20, 30])

In [53]:
# Subtract 10 from tensor
tensor - 10

tensor([ 0, 10, 20])

In [56]:
# Try out PyTorch built-in functions
torch.mul(tensor, 10)


tensor([100, 200, 300])

In [57]:
torch.add(tensor, 10)

tensor([20, 30, 40])

### Matrix multiplication

Two main ways to do matrix multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

More information on matrix multiplication - https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [60]:
# Element wise multiplication
print(tensor, "*" , tensor)
print(f"Equates to: {tensor * tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
Equates to: tensor([100, 400, 900])


In [62]:
# Matrix multiplication in PyTorch
torch.matmul(tensor, tensor) # Answer is 1400 because 10*10 + 20*20 + 30*30 = 1400

tensor(1400)